# -*- coding: utf-8 -*-
"""Breast Cancer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O6HydWALquCHUXtHpJlGVhMtXGglEzrR
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import sklearn.datasets

cancer_dataset=sklearn.datasets.load_breast_cancer()

print(cancer_dataset)

cancer_dataframe=pd.DataFrame(cancer_dataset.data,columns=cancer_dataset.feature_names)

print(cancer_dataframe)

cancer_dataframe['target']=cancer_dataset.target

print(cancer_dataframe)

cancer_dataframe.head()

cancer_dataframe.shape

cancer_dataframe.isnull()

X=cancer_dataframe.drop(['target'],axis=1)
Y=cancer_dataframe['target']
print(X)
print(Y)

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

print(X.shape,X_train.shape,X_test.shape)

from sklearn import linear_model
model=linear_model.LogisticRegression()
model.fit(X_train, Y_train)

train_predict=model.predict(X_train)

accuracy_train=accuracy_score(train_predict,Y_train)

print(accuracy_train)

test_predict=model.predict(X_test)

accuracy_test=accuracy_score(test_predict,Y_test)

input_data=(21.16,23.04,137.2,1404,0.09428,0.1022,0.1097,0.08632,0.1769,0.05278,0.6917,1.127,4.303,93.99,0.004728,0.01259,0.01715,0.01038,0.01083,0.001987,29.17,35.59,188,2615,0.1401,0.26,0.3155,0.2009,0.2822,0.07526
)

input_data_as_numpy_array=np.asarray(input_data)

input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)

prediction=model.predict(input_data_reshaped)

print(prediction)

